
COMMONSENSE_MAPPING = {'Antonym': 'antonym', 
	'AtLocation': 'at location', 
	'CapableOf': 'capable of', 
	'Causes': 'causes', 
	'CausesDesire': 'causes desire', 
	'CreatedBy': 'created by', 
	'DefinedAs': 'defined as', 
	'DerivedFrom': 'derived from', 
	'Desires': 'desires', 
	'DistinctFrom': 'destinct from', 
	'Entails': 'entails', 
	'EtymologicallyDerivedFrom': 'etymologically derived from', 
	'EtymologicallyRelatedTo': 'etymologically related to',
	'ExcludesFE': 'excludes frame element', 
	'FormOf': 'form of', 
	'HasA': 'has a', 
	'HasContext': 'has context', 
	'HasFirstSubevent': 'has first subevent', 
	'HasFrameElement': 'has frame element',
	'HasInstance': 'has instance',
	'HasLastSubevent': 'has last subevent',
	'HasLexicalUnit': 'has lexical unit',
	'HasPrerequisite': 'has prerequisite', 
	'HasProperty': 'has property',
	'HasSemType': 'has semantic type',
	'HasSubevent': 'has subevent',
	'HasSubframe': 'has subframe', 
	'InstanceOf': 'instance of', 
	'IsA': 'is a',
	'IsCausativeOf': 'is causative of',
	'IsInchoativeOf': 'is inchoative of',
	'IsInheritedBy': 'is inherited by',
	'IsPerspectivizedIn': 'is perspectivized in',
	'IsPOSFormOf': 'is part-of-speech form of',
	'IsPrecededBy': 'is preceded by',
	'IsUsedBy': 'is used by',
	'LocatedNear': 'location near', 
	'MadeOf': 'made of', 
	'MannerOf': 'manner of', 
	'MotivatedByGoal': 'motivated by goal',
	'object': 'object',
	'OMWordnetOffset': 'wordnet offset', 
	'NotCapableOf': 'not capable of', 
	'NotDesires': 'not desires', 
	'NotHasProperty': 'not has property', 
	'PartOf': 'part of', 
	'PartOfSpeech': 'part-of-speech',
	'PerspectiveOn': 'perspective on',
	'POSForm': 'part-of-speech form',
	'Precedes': 'precedes',
	'PWordnetSynset': 'wordnet synset',
	'ReceivesAction': 'received action', 
	'ReframingMapping': 'reframing mapping',
	'RelatedTo': 'related to', 
	'RequiresFE', 'requires frame element',
	'subject': 'subject',
	'SeeAlso': 'see also',
	'SimilarTo': 'similar to', 
	'subClassOf': 'subclass of',
	'SubframeOf': 'subframe of',
	'SubType': 'subtype',
	'SuperType': 'supertype',
	'SymbolOf': 'symbol of', 
	'Synonym': 'synonym', 
	'UsedFor': 'used for',
	'Uses': 'uses', 
        'DesireOf': 'desire of',
        'InheritsFrom': 'inherits from',
        'LocationOfAction': 'location of action',
	'dbpedia/capital': 'capital', 
	'dbpedia/field': 'field', 
	'dbpedia/genre': 'genre', 
	'dbpedia/genus': 'genus', 
	'dbpedia/influencedBy': 'influenced by', 
	'dbpedia/knownFor': 'known for', 
	'dbpedia/language': 'language', 
	'dbpedia/leader': 'leader', 
	'dbpedia/occupation': 'occupation', 
	'dbpedia/product': 'product'}
